model_args:
  graph_construction_args:
    graph_construction_share:
      root_dir: './'
      topology_subdir: 'DependencyGraph'
      share_vocab: true
      thread_number: 4
      port: 9000
      timeout: 15000

    graph_construction_private:
      edge_strategy: 'homogeneous'
      merge_strategy: 'tailhead'
      sequential_link: true
      as_node: false
