model_args:
  graph_construction_args:
    graph_construction_share:
      root_dir: null
      topology_subdir: 'IEGraph'
      share_vocab: true
      thread_number: 4
      port: 9000
      timeout: 15000

    graph_construction_private:
      edge_strategy: 'as_node'
      merge_strategy: null
